version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: proxmox-db
    env_file:
      - .env
    volumes:
      - db_data_proxmox:/var/lib/postgresql
    restart: unless-stopped


  api:
    build: .
    container_name: proxmox-api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./workspace:/workspace
      - ./terraform:/terraform

volumes:
  db_data_proxmox: